export enum LocationType {
  GameBoardPlace = 1,
  MiniBoardPlace,
  GardenCardsDeck,
  GameBoardSpace,
  EnhancementPile,
  ObjectiveTileSpace,
  PlayerIrrigationCard,
  PlayerGardeners,
  PlayerObjectiveMarkers,
  FirstPlayerMarkerPlace,
  GoldCoinsStock,
  PlayerGoldCoins,
  ToolsStock,
  PlayerTools,
  PlayerGarden,
  GardenerSpace,
  EmptyGarden,
  ObjectiveSpace,
  ScorePadPlace,
  ScorePadBox,
  AutomatonDeck,
  AutomatonGardeners,
  AutomatonObjectiveMarkers
}
